Make sure statuses are working correctly

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -25,27 +25,36 @@ jobs:
 
       - name: Build app and run tests
         id: run-tests
-        run: |
-          npm run test:ci:integration 2>&1 | tee output.txt
+        run: npm run test:ci:integration
         continue-on-error: true
 
-      - name: Extract test results between "failed" and "flaky"
-        id: test-results
-        run: |
-          output=$(cat output.txt)
+      # - name: Build app and run tests
+      #   id: run-tests
+      #   run: |
+      #     npm run test:ci:integration 2>&1 | tee output.txt
+      #   continue-on-error: true
 
-          extracted=$(echo "$output" | perl -n -e '/failed(.*?)flaky/ && print $1')
-            
-          echo "Extracted text: '$extracted'"
-          echo "extracted<<EOF" >> $GITHUB_OUTPUT
-          echo "$extracted" >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
+      # - name: Extract test results between "failed" and "flaky"
+      #   id: test-results
+      #   run: |
+      #     output=$(cat output.txt)
+
+      #     extracted=$(echo "$output" | perl -n -e '/failed(.*?)flaky/ && print $1')
+
+      #     echo "Test results: '$extracted'"
+      #     echo "extracted<<EOF" >> $GITHUB_OUTPUT
+      #     echo "$extracted" >> $GITHUB_OUTPUT
+      #     echo "EOF" >> $GITHUB_OUTPUT
+
+      # - name: Set failure workflow status 🚨
+      #   if: steps.run-tests.outcome != 'success'
+      #   run: |
+      #     echo '${{ steps.test-results.outputs.extracted }}'
+      #     exit 1
 
       - name: Set failure workflow status 🚨
         if: steps.run-tests.outcome != 'success'
-        run: |
-          echo '${{ steps.test-results.outputs.extracted }}'
-          exit 1
+        run: exit 1
 
       - name: Set successful workflow status ✅
         if: steps.run-tests.outcome == 'success'
